services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.0.0-beta.2
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    restart: unless-stopped